dof-dss/nidirect-site-modules

nidirect_workflow/css/admin.css, nidirect_workflow/nidirect_workflow.libraries.yml, nidirect_workflow/nidirect_workflow.links.menu.yml, nidirect_workflow/nidirect_workflow.module
Create 'My Dashboard' menu to replace 'My Workbench' from D7
=> D8 nid 250

nidirect_workflow/tests/src/Functional/AuditTest.php
Tests for audit processing on various content types
=> D8 nid 274

nidirect_related_content/nidirect_related_content.info.yml, nidirect_related_content/nidirect_related_content.module
This PR provides a module that gives a block to show the current position in the site themes taxonomy vocab, based on values from the node being viewed.
=> D8NID-282 Add custom module to control display of sidebar block view.

nidirect_breadcrumbs/nidirect_breadcrumbs.services.yml, nidirect_breadcrumbs/src/ContactBreadcrumb.php, nidirect_breadcrumbs/src/RecipeBreadcrumb.php, nidirect_common/nidirect_common.module
Provides the breadcrumb builder config needed to match the D7 site
=> D8NID-182 recipe search

nidirect_related_content/nidirect_related_content.info.yml, nidirect_related_content/nidirect_related_content.module, nidirect_related_content/src/Plugin/Block/RecipesByCourseBlock.php, nidirect_related_content/src/Plugin/Block/RecipesByIngredientBlock.php, nidirect_related_content/src/Plugin/Block/RecipesBySeasonBlock.php, nidirect_related_content/src/Plugin/Block/RecipesBySpecialDietBlock.php
PR to cover the definition of various sidebar blocks that generate facet URLs based on recipe node field values.
=> D8NID-184 related recipes blocks

nidirect_breadcrumbs/src/GpPracticeBreadcrumb.php, nidirect_common/nidirect_common.module, nidirect_gp/nidirect_gp.module, nidirect_gp/templates/block--views-exposed-filter-block--gp-practices-find-a-gp.html.twig, nidirect_gp/templates/node--gp-practice--teaser.html.twig
@DuttonMa a quick Q for you: the way I'm rendering fields through to my Twig template makes me think it's not quite right? Something you mentioned in your caching discussion made me think that being selective on specific field values misses the caching metadata, did I remember that right?
=> D8NID-194 GP practice preprocessing on search results and breadcrumb

nidirect_common/nidirect_common.module, nidirect_common/templates/block--views-exposed-filter-block--recipes-search-page.html.twig
=> Add template for recipes exposed filter block

nidirect_breadcrumbs/src/HealthConditionBreadcrumb.php, nidirect_breadcrumbs/src/RecipeBreadcrumb.php
Also pegged recipe search breadcrumb to use view route name rather than
fixed URL from expected string value.
=> D8NID-245 Fix breadcrumb path for health conditions search

nidirect_health_conditions/nidirect_health_conditions.module, nidirect_health_conditions/src/Plugin/Block/RelatedConditionsBlock.php
- Strip field-based preprocess code on search results; replace with rendered block plugin contents for consistency
=> D8NID-355 Add related conditions block plugin

nidirect_breadcrumbs/nidirect_breadcrumbs.services.yml, nidirect_breadcrumbs/src/DrivingInstructorsBreadcrumb.php, nidirect_breadcrumbs/src/SchoolClosuresBreadcrumb.php, nidirect_breadcrumbs/src/SearchBreadcrumb.php, nidirect_breadcrumbs/src/ThemesBreadcrumb.php, nidirect_breadcrumbs/tests/src/Nightwatch/Tests/contactBreadcrumbBuilder.js, nidirect_breadcrumbs/tests/src/Nightwatch/Tests/drivingInstructorsBreadcrumbBuilder.js, nidirect_breadcrumbs/tests/src/Nightwatch/Tests/schoolClosuresBreadcrumbBuilder.js, nidirect_breadcrumbs/tests/src/Nightwatch/Tests/searchBreadcrumbBuilder.js, nidirect_gp/src/Form/GpForm.php, nidirect_gp/src/Form/GpRevisionRevertForm.php, nidirect_gp/src/Form/GpRevisionRevertTranslationForm.php
Also includes some smaller fixes for existing breadcrumb handlers + nightwatch tests for them.
=> D8-NID 242 driving instructor breadcrumbs

nidirect_common/nidirect_common.module
Avoids interfering with other embedded entity view modes
=> Make view mode toggle more specific to Map paragraphs bundles

nidirect_breadcrumbs/nidirect_breadcrumbs.services.yml, nidirect_breadcrumbs/src/ContactBreadcrumb.php, nidirect_breadcrumbs/src/DrivingInstructorsBreadcrumb.php, nidirect_breadcrumbs/src/GovernmentContactBreadcrumb.php
- Drop deprecated/redundant path alias manager
- Some annotation tidyups
=> D8NID-244 Govt contacts path handling

.circleci/config.yml, nidirect_common/nidirect_common.module
Preprocess the views header render array to add the correct plural handling text. Related PR: https://github.com/dof-dss/nidirect-drupal/pull/143
=> Adjust how plural text is added to views header render array

nidirect_breadcrumbs/nidirect_breadcrumbs.services.yml, nidirect_breadcrumbs/src/BlackholeCrumb.php, nidirect_breadcrumbs/src/NullBreadcrumb.php
Catch known routes and paths we want to strip the breadcrumb display from
=> Breadcrumbs: remove from key routes and paths

nidirect_contacts/nidirect_contacts.module
The exposed filter changed from simple text filter to use the search API text field. This PR changes the array key needed to correctly adapt the text when you have searched for a key word/term.
=> D8NID-411 Alter the new exposed filter form element title

nidirect_common/nidirect_common.links.menu.yml, nidirect_temporary/nidirect_temporary.info.yml, nidirect_temporary/nidirect_temporary.module, nidirect_temporary/nidirect_temporary.routing.yml, nidirect_temporary/src/Controller/GovDeptController.php
Create temporary module to provide a route/controller for the Government Departments Contact page (will later be replaced by a 'Page' node)
This module is used by https://github.com/dof-dss/nidirect-drupal/pull/170
=> Contact views

nidirect_common/nidirect_common.links.menu.yml, nidirect_common/src/Plugin/Derivative/NidirectFeedbackmenuLinkDerivative.php, nidirect_common/src/Plugin/Menu/NidirectFeedbackMenu.php
Back-end solution to adding current page argument to the feedback link that appears in the main menu on every page
=> D8 nid 439 - fix feedback link on main menu

nidirect_breadcrumbs/src/GpPracticeBreadcrumb.php
Missed a route name change when adjusting the breadcrumb handler class
=> D8NID-451 Fix route name in breadcrumb handler

nidirect_gp/nidirect_gp.module
Tokenised version out of the box doesn't handle plurals
=> Add results count to the views header area

nidirect_common/tests/src/Nightwatch/Tests/contentTypeValidation.js
=> D8NID-571 Content type functional test

nidirect_news/src/Controller/NewsListingController.php
- Use 'page' query paramter presence/value to determine when to do this.
=> D8NID-532 Only show latest news + older news title when not on pager

nidirect_common/nidirect_common.module
Override erroneous date error that comes from Drupal core.
=> D8 nid 511

nidirect_common/nidirect_common.module
Override erroneous core date error message for more date fields.
=> D8 nid 590

nidirect_common/js/link-manager.js, nidirect_common/nidirect_common.libraries.yml, nidirect_common/nidirect_common.module
Self referencing links in specific regions are now changed to span elements with specific classes
=> D8NID-635 Add JS library to preprocess page: rewrite links

nidirect_media/nidirect_media.info.yml, nidirect_media/nidirect_media.module
- Add dependency to whatlinkshere module to fetch cross-referencing values
- Generate a new link element and replace the custom text field value in the view field object
=> Preprocess media view listing

nidirect_common/nidirect_common.module
Override incorrect date error messages from Drupal core in the scheduler tab.
=> D8 nid 627

nidirect_password_policy/nidirect_password_policy.info.yml, nidirect_password_policy/nidirect_password_policy.module
- Except password history; this may follow in a later iteration.
=> D8NID-468 Add small module to enforce all NICS policy rules

nidirect_common/nidirect_common.module
Also fixes an issue where the hide_content flag was being hidden instead of the featured_content flag.
=> Adds help text to the title field on node edit forms. 

nidirect_gp/src/Controller/GpSearchController.php
Some tweaks to gp practice search types and titles.
=> D8 nid 700 gp search location theming

nidirect_news/src/Controller/NewsListingController.php
Sticky flag introduced the risk of duplication or missing items due to the initial offset in the lower block. This commit ensures we add the node ids of the first as arguments to exclude from the latter, while retaining the ability to promote news items to the top block.
=> Avoid duplication between latest news items and older items block

nidirect_breadcrumbs/src/ContactBreadcrumb.php, nidirect_breadcrumbs/src/DrivingInstructorsBreadcrumb.php, nidirect_breadcrumbs/src/GovernmentContactBreadcrumb.php, nidirect_breadcrumbs/src/GpPracticeBreadcrumb.php, nidirect_breadcrumbs/src/HealthConditionBreadcrumb.php, nidirect_breadcrumbs/src/NewsBreadcrumb.php, nidirect_breadcrumbs/src/NodeThemesBreadcrumb.php, nidirect_breadcrumbs/src/NullBreadcrumb.php, nidirect_breadcrumbs/src/SchoolClosuresBreadcrumb.php, nidirect_breadcrumbs/src/SearchBreadcrumb.php, nidirect_breadcrumbs/src/TaxonomyTermThemesBreadcrumb.php
Provides preview breadcrumbs for certain nodes. 
Also cleaned up any phpcs warnings for all breadcrumb classes.
=> D8 nid 712

nidirect_common/nidirect_common.module
- Remove placeholder from title field.
- Tweaks to descriptions for title and a couple of flags
- Descriptions are only set if empty (to allow them to be set in the UI)
=> Tweaks to help text defined in code

nidirect_common/nidirect_common.module
fix error when discarding draft
=> D8 nid 740

nidirect_common/tests/src/Nightwatch/Tests/AdminTest.js, nidirect_common/tests/src/Nightwatch/Tests/AppsTest.js, nidirect_common/tests/src/Nightwatch/Tests/AuthenticatedTest.js, nidirect_common/tests/src/Nightwatch/Tests/AuthorTest.js, nidirect_common/tests/src/Nightwatch/Tests/DrivingSupervisorTest.js, nidirect_common/tests/src/Nightwatch/Tests/EditorTest.js, nidirect_common/tests/src/Nightwatch/Tests/GPAuthorTest.js, nidirect_common/tests/src/Nightwatch/Tests/HCAuthorTest.js, nidirect_common/tests/src/Nightwatch/Tests/HCSupervisorTest.js, nidirect_common/tests/src/Nightwatch/Tests/NewsSupervisorTest.js, nidirect_common/tests/src/Nightwatch/Tests/SupervisorTest.js
- Move NIDirect specific Nightwatch tests out of Origins and into the nidirect_common module
=> D8 nid 512

nidirect_common/nidirect_common.install
Create NIDirect specific users for Nightwatch testing in hook_install - and delete them in hook_uninstall
=> D8 nid 512 c

nidirect_landing_pages/js/landing_listing.js, nidirect_landing_pages/nidirect_landing_pages.module
Bug fix to landing page Ajax error
=> D8 nid 823

nidirect_common/tests/src/Nightwatch/Tests/regressions/contactsSearch.js, nidirect_contacts/tests/src/Nightwatch/Tests/contactPageElements.js
Updated selectors for old contacts tests as the markup had changed.
=> D8NID0-835 regression test and fixed contacts tests

nidirect_gp/nidirect_gp.links.menu.yml
Create new menu entries for GP reports.
See also https://github.com/dof-dss/nidirect-drupal/pull/430/
=> D8 nid 354

nidirect_health_conditions/src/Plugin/Block/RelatedConditionsBlock.php
Need this in relation to https://github.com/dof-dss/nicsdru_nidirect_theme/pull/158
=> Tweak theme suggestion for related conditions item list.

nidirect_common/nidirect_common.module, nidirect_gp/src/Controller/GpSearchController.php, nidirect_homepage/src/Plugin/Block/FeaturedContentBlock.php
Some small fixes from reports in the error log while browsing the site.
=> Misc fixes

nidirect_contacts/nidirect_contacts.module, nidirect_search/README.md, nidirect_search/nidirect_search.module
Gets the index hash from config rather than having it hard coded. Streamlines some of the query preprocessing, too.
Snuck in a small tidyup in contacts module to remove two unused variables.
=> D8NID-912 improve search elevation handling

nidirect_gp/js/gp-location-search.js, nidirect_gp/src/Controller/GpSearchController.php
Whether its a location based search, or a fulltext search, make the "Use my location" button always available.  Change the text of the button to "Reset my location" when already displaying location based results.
=> D8 nid 772 gp search form fixes

nidirect_common/inc/form_alter.inc
Make the 'sticky at top of lists' option available on contacts.
=> Hide 'sticky at top of lists' option on nodes except news and contacts.

nidirect_related_content/nidirect_related_content.module
Subtheme is likely not a consideration for taxonomy pages but adding it anyway for consistency
=> Improve handling of theme/subtheme values for views args

nidirect_cold_weather_payments/config/optional/field.field.node.cold_weather_payment.field_cwp_payments_period.yml, nidirect_cold_weather_payments/config/optional/field.field.node.cold_weather_payment.field_cwp_payments_triggered.yml, nidirect_cold_weather_payments/config/optional/field.storage.node.field_cwp_payments_period.yml, nidirect_cold_weather_payments/config/optional/field.storage.node.field_cwp_payments_triggered.yml, nidirect_cold_weather_payments/config/optional/nidirect_cold_weather_payments.weather_station.aldergrove.yml, nidirect_cold_weather_payments/config/optional/nidirect_cold_weather_payments.weather_station.castlederg.yml, nidirect_cold_weather_payments/config/optional/nidirect_cold_weather_payments.weather_station.glenanne.yml, nidirect_cold_weather_payments/config/optional/nidirect_cold_weather_payments.weather_station.katesbridge.yml, nidirect_cold_weather_payments/config/optional/nidirect_cold_weather_payments.weather_station.magilligan.yml, nidirect_cold_weather_payments/config/optional/nidirect_cold_weather_payments.weather_station.stormont.yml, nidirect_cold_weather_payments/config/optional/nidirect_cold_weather_payments.weather_station.thomastown.yml, nidirect_cold_weather_payments/config/optional/node.type.cold_weather_payment.yml, nidirect_cold_weather_payments/config/schema/nidirect_cold_weather_period.schema.yml, nidirect_cold_weather_payments/nidirect_cold_weather_payments.services.yml, nidirect_cold_weather_payments/src/Entity/WeatherStationEntity.php, nidirect_cold_weather_payments/src/Plugin/rest/resource/ColdWeatherPaymentResource.php, nidirect_cold_weather_payments/src/Service/ColdWeatherPaymentsService.php, nidirect_cold_weather_payments/tests/src/Kernel/ColdWeatherPaymentsTest.php
- Moved payments processing from REST resource to it's own service.
- Copied payments and stations entity config to module for import during test.
- Created basic kernel test setup.
=> D8 nid 995

nidirect_common/inc/form_alter.inc
- open relations section by default
- enable chosen on the parent select element
- allow only one parent to be selected
=> D8NID-1047 - tweaks to add term form for site themes:

nidirect_landing_pages/nidirect_landing_pages.module
=> D8NID-1052

nidirect_common/nidirect_common.services.yml, nidirect_common/src/LinkitSuggestionManager.php
- Detect and prune search strings with absolute paths in them
- Inject request stack service
=> D8NID 1060

nidirect_breadcrumbs/nidirect_breadcrumbs.services.yml
- Bug fix - Increase priority of 'news' breadcrumb
=> D8NID-1014

nidirect_webforms/js/multiple-webform-submit.js, nidirect_webforms/nidirect_webforms.libraries.yml, nidirect_webforms/nidirect_webforms.module
Added JQuery to deal with more than one webform on a page
=> D8NID-1088

nidirect_driving_instructors/nidirect_driving_instructors.module
with radios compatible with facets and add help text to top of the form (hidden when results are shown)
=> Driving instructors: replace categories exposed filter 

nidirect_common/inc/form_alter.inc, nidirect_common/nidirect_common.module
Implement custom taxonomy term validator in order to solve missing parent problem
=> D8NID-1092

nidirect_cold_weather_payments/src/Form/ColdWeatherPaymentCheckerForm.php
Enable the form to accept a full NI postcode plus changes to theme it up and add styled error message.
=> D8 nid 1094 cold weather payments form

nidirect_common/nidirect_common.module
- Show 404 'page not found' for invalid publications pages
=> D8 nid 1098

nidirect_webforms/nidirect_webforms.module
Add honeypot field to all webforms
(Relates to https://github.com/dof-dss/nidirect-drupal/pull/645)
=> D8NID-1104

nidirect_taxonomy_navigator/src/Form/TaxonomyNavigatorForm.php
Adds a search button inline with the taxonomy search input.
=> D8NID-1136 : Taxonomy navigator search

nidirect_cold_weather_payments/src/Form/ColdWeatherPaymentCheckerForm.php
Fix issue with empty error msg balloon and clear errors when postcode input gets focus
=> D8NID-1132 : CWP checker fix

nidirect_webforms/nidirect_webforms.module
Due to clash with wizard controls on site feedback form
=> Remove hidden CSS class set by webform conditional fields

nidirect_common/css/admin.css, nidirect_common/inc/preprocess.inc, nidirect_common/nidirect_common.libraries.yml
Remove in favour of adding to origins theme
=> Revert "D8 nid 1128"

nidirect_landing_pages/nidirect_landing_pages.module
Allows us to restrict editor options on layout builder block routes
=> Add process callback on element format info

nidirect_contacts/nidirect_contacts.module
Relates to https://github.com/dof-dss/nidirect-drupal/pull/686
=> Preprocess the views query and result, let SQL handling sort order

nidirect_contacts/nidirect_contacts.module
Slightly convoluted extra preprocesing needed to take into account case sensitivity of array_multisort and the odd thing views needs with the 'index' property which we can't update in array_multisort at the same time.
=> Adjustment to contacts sorting process

nidirect_gp/nidirect_gp.module, nidirect_gp/nidirect_gp.services.yml, nidirect_gp/src/EventSubscriber/GeocoderApiKeyUpdate.php
Ensure that the Google Maps API key that is used for geocoding is set correctly from the environment variable after every config import.
=> D8NID-1210

nidirect_common/nidirect_common.module
Further bug fix to taxonomy views
=> D8NID-1228

nidirect_common/inc/preprocess.inc
=> Add additional info footer text where it's available on a theme term entity

nidirect_gp/tests/src/Kernel/GPPracticeTest.php
Added missing dependency that was causing PHPUnit tests to fail in CircleCI
=> D8NID-1250

nidirect_common/inc/preprocess.inc
Underlying library struggles to parse these correctly and adding a fix there is significantly more complex.
=> Adjust the telephone text for international freephone numbers.

nidirect_common/inc/form_alter.inc
Relates to https://github.com/dof-dss/nidirect-drupal/pull/722
=> Disable form actions if the node has the locked flag set.

nidirect_related_content/src/RelatedContentManager.php
Array multisort is case sensitive so add a sort value that's normalised to lowercase to assist with natural sorting
=> Normalise content list to lowercase for natural sorting

nidirect_webforms/nidirect_webforms.module
Data affected here is cleaned up prior to storage and/or re-use in other handlers, eg: email
=> Strip HTML from two known webforms and elements

nidirect_contacts/src/Plugin/Field/FieldFormatter/NIDirectTelephoneLinkFormatter.php
Ain't gonna win no beauty contest but fixes the issue when the contact uses the same number for text phone and other contact labels.
=> D8NID-1214 ~ Fix prefix issue when identical numbers are used

nidirect_common/nidirect_common.module
Change cron task to process audit queue in one pass.
(Linked to https://github.com/dof-dss/nidirect-d8-mig-mods/pull/119 )
=> D8 nid 1298

nidirect_money_advice_articles/config/install/migrate_plus.migration.money_advice_service_rss_articles.yml
Super irritating process plugin order needed otherwise body text isn't saved/silently fails. See https://www.drupal.org/docs/8/api/migrate-api/migrate-process-plugins/migrate-process-overview for detail
=> D8NID-1253

nidirect_gp/src/GpAutocompleteMatcher.php
Fixes:
* adding a GP to a practice
* changing author on an article
* adding a parent to a contact (the original problem)
* Autocomplete on featured content lists
=> Fix issue with broken autocomplete widgets

nidirect_common/inc/form_alter.inc
Disable 'Upload latest Fastly VCL' button on Fastly admin form.
=> D8 nid 1353

nidirect_webforms/nidirect_webforms.module
Prevents submission of HTML; supports the site without the use of honeypot to block unhelpful form submissions
=> Validation callback for specific webforms

nidirect_common/nidirect_common.module
=> D8NID-1363

nidirect_contacts/src/Plugin/Block/ContactAzBlock.php, nidirect_gp/js/gp-location-search.js, nidirect_gp/nidirect_gp.module
Label and aria role description fixes for GP practices search and Contacts search plus add skip link to contacts A to Z menu
=> A11y fixes

nidirect_common/nidirect_common.module
Fixes major bug preventing CET reverting to previous revisions.
https://digitaldevelopment.atlassian.net/browse/D8NID-1426
=> Fixes "Call to a member function hasField() on string"

nidirect_common/nidirect_common.module
Merges D8NID-1426-hotfix into main
=> Merge dev to main

nidirect_landing_pages/nidirect_landing_pages.module
Fixes issue preventing editing of blocks on landing pages
=> D8NID-1543
