nidirect_common/tests/src/Functional/DrivingInstructorTest.php
nidirect_common/tests/src/Functional/GPPracticeTest.php
nidirect_gp/src/Controller/GpController.php
nidirect_gp/src/Form/GpForm.php
nidirect_gp/src/Form/GpRevisionDeleteForm.php
nidirect_gp/src/Form/GpRevisionRevertForm.php
nidirect_school_closures/src/SchoolClosure.php
nidirect_school_closures/tests/src/Kernel/C2kschoolsSchoolClosuresServiceTest.php
nidirect_school_closures/tests/src/Kernel/SchoolClosuresTest.php
nidirect_workflow/nidirect_workflow.module

drupal-check and phpcs were throwing errors about some deprecated code, autoloading of classes and code not compliant with drupal.org coding standards.
This PR aims to fix those. Has been validated with:
`lando drck drupal8/web/modules/custom`
and
`lando phpcs`

D8NID-267 ~ fix deprecated code warnings

---

nidirect_common/tests/src/Functional/DrivingInstructorTest.php
nidirect_common/tests/src/Functional/GPPracticeTest.php
nidirect_common/tests/src/Kernel/DrivingInstructorTest.php
nidirect_common/tests/src/Kernel/GPPracticeTest.php

Create Kernel tests for GP Practice and Driving Instructors.
Corrections to existing browser tests.
Left browser tests in place as Kernel tests required mocking of content type and fields.

D8 nid 259

---

nidirect_breadcrumbs/nidirect_breadcrumbs.services.yml
nidirect_breadcrumbs/src/SearchBreadcrumb.php

Search results pages do not show a breadcrumb. Rather than preprocess the heck out the template for that page (as per D7) we can introduce a new breadcrumb handler class that responds to the route name and can, in this case, set an empty array of links which in turn means nothing is rendered.
In future, if we need to adjust other views displays - we only need to put some more conditional checks on the route and can adapt what is displayed in each instance.

Add a search breadcrumb handler class

---

nidirect_breadcrumbs/nidirect_breadcrumbs.services.yml
nidirect_breadcrumbs/src/ContactBreadcrumb.php
nidirect_breadcrumbs/src/GpPracticeBreadcrumb.php
nidirect_breadcrumbs/src/HealthConditionBreadcrumb.php
nidirect_breadcrumbs/src/NewsBreadcrumb.php
nidirect_breadcrumbs/src/RecipeBreadcrumb.php
nidirect_breadcrumbs/src/ThemesBreadcrumb.php
nidirect_breadcrumbs/src/UmbrellaBodyBreadcrumb.php

Node view page provides the node object, revision listing does not so it
needs to be loaded if the node parameter is not already a fully
instantiated node object

Inject entity type manager to obtain full node object when required

---

nidirect_common/nidirect_common.links.menu.yml

These can either remain in situ, or can be replaced with content style menu links added via the UI as/when required as the build progresses

Placeholder menu links for main nav

---

nidirect_breadcrumbs/src/NewsBreadcrumb.php
nidirect_news/nidirect_news.info.yml
nidirect_news/nidirect_news.module
nidirect_news/nidirect_news.routing.yml
nidirect_news/src/Controller/NewsListingController.php

Opted to use two views embed displays managed with a controller for maximum flexibility (ie: if you want to introduce something above/below/between the content lists) that might traditionally be harder on just a views page display. This also mirrors the same approach taken for contacts which had some slightly more bespoke requirements.

D8NID-192 news

---

nidirect_common/src/Plugin/Block/SiteSearchBlock.php

Necessary to allow exposed filter to work correctly. Normally you can add a views block display and the AJAX filters work for your needs, but because we introduce search_api_autocomplete we want to either move the user on form submit to the URL of the item selected or, if nothing, to the default form action path. AJAX filters don't allow this, so with a small block to wrap the display we can get around this limitation.

Add block wrapper around views embed display

---

nidirect_site_themes/nidirect_site_themes.info.yml
nidirect_site_themes/nidirect_site_themes.module
nidirect_site_themes/nidirect_site_themes.services.yml
nidirect_site_themes/src/Routing/TaxonomyRouteSubscriber.php
nidirect_site_themes/src/TaxonomyVocabAccess.php

Site editors presently have the ability to add/edit/view terms in the site topics (now site themes) vocabulary and this is presented by using `taxonony_access_fix` to make vocab perms more granular and `views_tree` to visualise/present the hierarchy. There are some problems here because: it's not searchable, it's paged and adding terms uses the core taxo forms making for a somewhat janky UX.
This PR compliments another PR that together provides:
- Taxonomy manager contrib module to provide a full, visualised hierarchy of terms, ability to edit/add/move in situ, and search.
- Taxonomy access fix to make per-vocab terms more granular so we can lock off access to non-essential vocabs.
- nidirect_site_themes custom module to fudge about with how taxonomy_manager presents things, using the …

D8NID-258 Add custom module to mediate access to taxonomy terms

---

nidirect_gp/nidirect_gp.links.task.yml

Re design of user dashboard, centralise everything around the main admin content view.

Move 'GPs' menu option down to secondary tab on content page

---

nidirect_breadcrumbs/nidirect_breadcrumbs.services.yml
nidirect_breadcrumbs/src/SchoolClosuresBreadcrumb.php
nidirect_school_closures/nidirect_school_closures.module

- Use service container parameters to define path match for specific
page(s) to display the breadcrumb and/or closures details on.
Haven't touched the WYSIWYG profiles to use the token embed button which was the originally expected route for this to take.

Add new breadcrumb builder class and render closures element

---

nidirect_breadcrumbs/src/ContactBreadcrumb.php
nidirect_breadcrumbs/src/GpPracticeBreadcrumb.php
nidirect_breadcrumbs/src/HealthConditionBreadcrumb.php
nidirect_breadcrumbs/src/NewsBreadcrumb.php
nidirect_breadcrumbs/src/RecipeBreadcrumb.php
nidirect_breadcrumbs/src/UmbrellaBodyBreadcrumb.php
nidirect_breadcrumbs/tests/src/Nightwatch/Tests/applicationBreadcrumbBuilder.js
nidirect_breadcrumbs/tests/src/Nightwatch/Tests/contactBreadcrumbBuilder.js
nidirect_breadcrumbs/tests/src/Nightwatch/Tests/gpPracticeBreadcrumbBuilder.js
nidirect_breadcrumbs/tests/src/Nightwatch/Tests/healthConditionBreadcrumbBuilder.js
nidirect_breadcrumbs/tests/src/Nightwatch/Tests/newsBreadcrumbBuilder.js
nidirect_breadcrumbs/tests/src/Nightwatch/Tests/recipeBreadcrumbBuilder.js

- Amend CSS selector + timeout limits on nightwatch tests.
- Make breadcrumb builder classes consistent for checking node values
and bundle types

Fix nightwatch tests for breadcrumbs on node types.

---

nidirect_common/nidirect_common.module
nidirect_common/nidirect_common.services.yml
nidirect_common/src/InvalidateTaxonomyListCacheTags.php

Add hooks to invalidate custom cache tags for taxonomy term view pages.
See other associated PRs:
- https://github.com/dof-dss/nicsdru_nidirect_theme/pull/19/files (preprocess function)
- https://github.com/dof-dss/nidirect-drupal/pull/107 (new views)

D8 nid 367

---

nidirect_driving_instructors/nidirect_driving_instructors.module

Ensure search plugin exists before trying to invoke a function on it, avoids tripping a null error

D8NID-379: error on search plugin usage

---

nidirect_common/nidirect_common.services.yml
nidirect_common/src/InvalidateTaxonomyListCacheTags.php

Add cache invalidation processing for parent term of campaign
Associated PRs:
dof-dss/nidirect-site-modules#108 - add view display for campaigns
dof-dss/nicsdru_nidirect_theme#20 - allow for campaigns overriding taxonomy terms on listing pages

Campaign aliases

---

nidirect_common/nidirect_common.module
nidirect_gp/src/Form/GpRevisionRevertForm.php
nidirect_gp/src/Form/GpRevisionRevertTranslationForm.php

CKEditor now doesn't permit iframe style dynamic maps in the editorial preview. This code allows us to dynamically switch between Google static maps and (dynamic) Google maps when we move between viewing content and writing content.

Preprocess entity embed elements to swap between dynamic and static maps

---

nidirect_common/nidirect_common.module

Bug fix to avoid '_Call to undefined method Drupal\media\Entity\Media::getParagraphType()_' when viewing landing pages.

bug fix to avoid error when 'getParagraphType' method does not exist

---

nidirect_contacts/nidirect_contacts.module

Use of `unset` meant that views couldn't get at the values of the form elements meaning things like sort ordering weren't working correctly. `hide` sets a flag to say the element has already been rendered, but ensures later form handling can still access the values from those elements.

DNID-405 contacts refinements

---

nidirect_breadcrumbs/nidirect_breadcrumbs.services.yml
nidirect_breadcrumbs/src/NewsBreadcrumb.php

Thought this was already working before, but guess not! It is now.

Add news view route name to list of routes covered by nullbreadcrumb

---

nidirect_common/inc/landing_page.redirects.inc
nidirect_common/nidirect_common.module
nidirect_gp/src/PostcodeExtractor.php

Two key things in this PR:
1. It aims to avoid creating redirects for new landing pages when they already exist.
2. It aims to warn editors when saving a new landing page whether another already exists for that theme value. That should ward off any duplicate content issues and, conversely, also reduce the likelihood of duplicate redirects being created.
There's a fair bit of refactoring to move a lot of code shared between entity insert + update into a separate .inc file for better readability.

D8 nid 460 landing page duplicates and redirectds

---

nidirect_landing_pages/nidirect_landing_pages.module

I originally had this using '#access' but changed it to '#hidden' during the code review.
It turns out that it does need to be '#access' after all, I hadn't fully tested the change (only noticed it when it broke in my demo yesterday !)

D8NID-498 bugfix - hide listing field

---

nidirect_common/tests/src/Nightwatch/Tests/contentTypeValidation.js

- Past config import bugs (mostly from core) have meant partially
created content types have been left 'dangling' with no means to
recreate or remove without a full reinstall.
- This check will, at the very least, allow us to detect this a little
sooner if it does happen again.
This test will need connecting up with the Circle CI jobs/triggers to make this return any significant value. Otherwise, we're relying on devs to execute the tests which isn't a terribly reliable approach :)

Add functional JS test to check content type presence.

---

nidirect_common/js/view-media-entity-browser.js
nidirect_media/nidirect_media.module

buttons
- Only want to disable the browser widget's button to avoid submitting
empty selections.
- Without the indicator class, the inline entity form's save button also
disables meaning you can't create new inline-content.

Set a server-side class to aid with disabling entity browser widget

---

nidirect_search/nidirect_search.module

Unclear why the language undefined dictionary fills but the langcode 'en' does not. Either way, this small change ensures we can query one. They happen to contain the same contents anyhow (for now).

D8NID-476 Set dictionary language for suggestions

---

nidirect_search/nidirect_search.module

Moves most of the prior fixed, XML based values into a runtime query alter hook. Existing values are hard coded (for now) but could be changed to come from an admin settings form in future.

Move XML Solr config into module hook for runtime alterations

---

nidirect_breadcrumbs/nidirect_breadcrumbs.services.yml

Looks like the breadcrumb handler class needed a boost to its priority. Without it, views tries to take over and we just need it to move aside in this instance.

D8NID-628 Boost service priority to steal control back from views

---

nidirect_common/nidirect_common.module

As with https://github.com/dof-dss/nidirect-drupal/pull/334, it has occurred to me to make use of #placeholder in addition to #description to display help text to the user.

Adds help text to the title field #placeholder as well as #description.

---

nidirect_common/nidirect_common.module

- Clashes with core media library functionality.

Exclude clientside_validation on node/media add/edit forms.

---

nidirect_common/nidirect_common.module

Ensures it is rendered in the correct element of the page, respecting broader page container boundaries.

D8NID-717 Set banner render array in correct page region

---

nidirect_common/nidirect_common.info.yml
nidirect_common/nidirect_common.services.yml
nidirect_common/src/Controller/LinkitAutocompleteController.php
nidirect_common/src/LinkitResultManager.php
nidirect_common/src/NidirectCommonServiceProvider.php
nidirect_common/src/Routing/RouteSubscriber.php

- Required due to a lack of preprocess or easy override (via dependecy injection) of underlying service classes.
May be useful to split into an origins module if Unity requires it?

Take over some of linkit module's functionality

---

nidirect_homepage/src/Plugin/Block/FeaturedContentBlock.php
nidirect_news/src/Controller/NewsListingController.php

A PR that adjusts the news controller to:
- Replace the generic views render array for 'latest news' with something to load a featured content list tagged with a specific tag,
- take the node ids it provides and inject them into a modified views display as arguments.
So essentially only uses views to present the data so we don't need to modify the frontend, but rather than let it do the querying part we use contextual arguments to inject the things we want it to show based on our controller's data query.

D8NID-764 news queue

---

nidirect_common/nidirect_common.module
nidirect_common/tests/src/Functional/DrivingInstructorTest.php
nidirect_common/tests/src/Functional/GPPracticeTest.php

Turn off strict schema checking so that PHPUnit tests can run.
This is necessary because some contrib modules (like eu_cookie_compliance and google_analytics_counter) export config that doesn't match their defined schema.
Also fix 'undefined index' bug in preprocess function.

D8 nid 662

---

nidirect_news/nidirect_news.module
nidirect_news/tests/src/Nightwatch/Tests/featuredContentListViewSwitch.js

Also adds a regression test to detect anything like it in future.

D8NID-812 Only swap render array on news FCL node, not homepage.

---

nidirect_common/nidirect_common.module
nidirect_common/tests/src/Nightwatch/Tests/layoutBuilderRegressions.js

Nice single-liner to strip the extra cruft the clientside validation module adds on this route.

Turn off on layout builder block form

---

nidirect_common/nidirect_common.module

Well this threw me down the garden path. There are a range of hooks allowing you to adjust the SHS widget's options and, at face value, it seems to only show get methods on the widget object making it hard to set a new value in the way it would expect.
However, because the widget object type is a translated markup object, I'm proposing to cheat a little here and replace the value with a translated text value. As far as I can tell, it seems like a safe operation.

D8NID-719 Change label on shs default value to match regular dropdown options

---

nidirect_common/tests/src/Nightwatch/Tests/regressions/layoutBuilder.js

The unique title field check has an AJAX call which introduces a slight pause when moving away from the title field. We need to both trigger a key press to activate the JS event and then briefly pause to let it do its thing before moving onto populating the rest of the form.

Fix handling of pause when populating title field

---

nidirect_news/src/Controller/NewsListingController.php

Ensures the "Older news items" title is only output on the first page of news.

Output 'Older news items' heading on initial news landing page only.

---

nidirect_health_conditions/css/search-conditions-prompt.css
nidirect_health_conditions/js/search-conditions-prompt.js
nidirect_health_conditions/nidirect_health_conditions.libraries.yml
nidirect_health_conditions/nidirect_health_conditions.module

Adds JS/CSS to the health conditions module to display the "search conditions prompt" when viewing health conditions on a narrow screen.  
The prompt appears at the bottom of the screen after scrolling down a bit.  Clicking the prompt skips you down to the search/a-z widget at the bottom of the page and sets focus on the search input.

Health conditions search prompt

---

nidirect_health_conditions/nidirect_health_conditions.module
nidirect_health_conditions/nidirect_health_conditions.routing.yml
nidirect_health_conditions/src/Controller/HealthConditionsListingController.php

Removes page title callback and some header massaging from health conditions module.  Using hook_preprocess_page_title in the theme to add bits and pieces of helpful information - see https://github.com/dof-dss/nicsdru_nidirect_theme/pull/159

D8 nid 154 health conditions az

---

nidirect_breadcrumbs/src/TaxonomyTermThemesBreadcrumb.php

Prevent breadcrumb showing just a home link.

Add home link to breadcrumb if there are ancestor terms to show 

---

nidirect_common/nidirect_common.module

Alter the system performance admin screen so that a 'Browser and proxy cache maximum age' of 1 year may be selected.
Also add an informative suffix to make it clear that this has been done.
Related to https://github.com/dof-dss/nidirect-drupal/pull/465

D8 nid 842

---

nidirect_common/inc/form_alter.inc
nidirect_common/nidirect_common.module
nidirect_common/tests/src/Nightwatch/Tests/regressions/layoutBuilder.js

A little more dancing around this module. It's not practical to target a multitude of form ids and routes, so inverting this and only letting it act on webform forms seems more pragmatic.
It seems to still need two hooks at the very least, but the `#after_build` removal is something from before that can probably stay for now even though it might not be needed with the page_attachments_alter and this hook in place,.

Instruct clientside_validation module not to operate on non-webform forms

---

nidirect_news/nidirect_news.module
nidirect_news/src/Controller/NewsListingController.php
nidirect_news/src/Plugin/Block/FeaturedNewsBlock.php

Re-use as much of the broader news views display approach as possible. Essentially use views as a rendering method for news node ids passed in as contextual arguments. Featured news display differs from the 'latest news' one on the landing page because it uses fields (like the block display) for the sidebar

D8NID-822 Wrap featured news embed into a block

---

nidirect_contacts/nidirect_contacts.module

Spotted during testing: `contacts/jobs-benefits-offices` - a sneaky 'United Kingdom' value is rendered because the address field only contains the default country value, isn't empty and then renders to the page.
Now treating it with the same rules as the location field for consistency.

D8NID-910 Also hide address field if it only contains a country value

---

nidirect_common/nidirect_common.module
nidirect_common/tests/src/Nightwatch/Tests/regressions/layoutBuilder.js

Turns out clientside_validation cannot be turned off with just the hook it proposes you use.

Switch regression test to use xpath for some elements and reinstate hook to alter page attachments.

---

nidirect_common/nidirect_common.module

Surprised this worked before but perhaps there has been a shift in the underlying render array. In any case, this correctly references the array segments allowing the extra CSS class to be pruned off allowing the revisions to be viewed on their own page.

Fix for incorrectly referenced array in sidebar buttons

---

nidirect_common/nidirect_common.module

Causes issues when checking for region/variable contents in page templates, because we don't know if the render array is empty because it is build/rendered afterwards by the lazy builder service

Switch off lazy builder placeholders on some blocks

---

nidirect_contacts/nidirect_contacts.module

May also fix D8NID-991. Slightly tricky issue whereby `getRequiredFields()` may sometimes be null, so adding an extra check in this PR to try and avoid calling that function unless we're sure the address config is not empty.

D8NID-989 Extra check on array element before attempting to access method on it

---

nidirect_health_conditions/nidirect_health_conditions.module

Fixes an issue with more useful links on health conditions where external links had markup for external link icons twice.

Remove code adding external link icon markup - this is handled in JS

---

nidirect_health_conditions/nidirect_health_conditions.module

Easy way to ensure consistency between db based queries and Solr queries (all use entity status as a filter). Also allows us to avoid writing bespoke Solr processor plugins to do the same thing in a more convoluted manner.

Keep HC alt title node status in sync with parent HC node status

---

nidirect_common/inc/form_alter.inc
nidirect_common/nidirect_common.services.yml
nidirect_common/src/Routing/RouteSubscriber.php

See JIRA ticket for full context. TL;DR: provides editors option to edit media fields via button on the ckeditor modal form. Also tweaks the wording to make it clear the ckeditor is for overriding any canonical field values.

D8NID-996: Adjust media edit dialog route title and add button to canonical form

---

nidirect_health_conditions/nidirect_health_conditions.module

Problems with adjusting the node title of the parent node meant it was
easier to drop in a search_result view mode template for the HCA node
and just focus on adding the summary value from the HC node into the
render array. Keeps things simpler!

Slight re-think on handling parent HC nodes.

---

nidirect_health_conditions/nidirect_health_conditions.module

Additionally, preprocess the url value in search result view mode so we don't point at the HCA node itself, rather the parent condition node.

Creating a new HC node should also sync the HCA node's publish status.

---

nidirect_taxonomy_navigator/nidirect_taxonomy_navigator.services.yml
nidirect_taxonomy_navigator/src/TaxonomyAdminBreadcrumb.php

Intends to provide a more consistent UX when adding new terms to a vocab (less crossover with core taxonomy module's breadcrumb trail)

Add breadcrumb builder class for stealing (some) control from core taxo module

---

nidirect_driving_instructors/nidirect_driving_instructors.module

Without this, the facet link is stripped leaving text alone which is not useful to the end-user

Turn off JS from link-manager.js on facet links

---

nidirect_landing_pages/nidirect_landing_pages.module

Just found this bug when looking at the article teasers functionality

allow for nodes that have no summary field

---

nidirect_landing_pages/nidirect_landing_pages.module

Do not show the 'manually control listing' checkbox or the listing fields when editing or creating a landing page node. This functionality is now available in layout builder only.

hide article teaser listing fields on node edit form

---

nidirect_driving_instructors/nidirect_driving_instructors.module

Quick bug fix - remove category radios altogether from the search results page instead of outputting as a hidden input.  The hidden input leads to broken pager links due to the addition of an extra query parameter f[0]=categories:all.

Driving instructors search mods

---

nidirect_cold_weather_payments/src/Form/ColdWeatherPaymentCheckerForm.php

Fixes the following issues with the cold weather payment checker form:
- when entering an invalid postcode, the resulting error message would persist even after re-submitting the form with a valid postcode
- after triggering an error on the form and then refreshing the page (or even browsing to another page), an error message would be shown at the top of the page

D8NID-1094 Cold Weather Payment checker validation fixes

---

nidirect_landing_pages/nidirect_landing_pages.module

For some custom blocks like accordions and video and caption, users need control over displaying the block title.  So we can't have this option hidden.  It would be nice to hide it for certain types of block (like cards where the title should always be visible) - but this is difficult to do (see https://www.drupal.org/project/drupal/issues/3028391).  So we are forced to make the option available for all blocks.

Layout builder custom blocks - re-enable display title checkbox

---

nidirect_common/src/LinkitSuggestionManager.php
nidirect_homepage/src/Plugin/Block/FeaturedContentBlock.php

There's a fair bit going on there but in summary:
- Adds block form + submit handlers to define options for FCL nodes to reference, and a way to store them in config.
- Looks up the config values when building the block, rather than using taxonomy terms from the tags vocab.
Full disclaimer: relies on FCL nodes to exist to work. Migrations/shifting IDs may cause some headaches here unless we can keep block config up to date after each migration run.

Use block config instead of taxonomy tags for referenced FCL nodes

---

nidirect_common/nidirect_common.module

This PR tweaks the logic for showing the admin toolbar Edit button so that is available to editors:
- when using the layout builder on a landing page
- on the homepage so that they easily edit features.

Tweaks to visibility logic for admin toolbar edit button

---

nidirect_common/js/application-links-notranslate.js
nidirect_common/js/translation-help.js
nidirect_common/nidirect_common.libraries.yml
nidirect_common/nidirect_common.module
nidirect_common/src/LinkitSuggestionManager.php
nidirect_common/src/Plugin/Block/TranslationHelpBlock.php

A simple block to output the translation help link plus javascript to process the Google Translate links on /articles/translation-help and add in the referring URL to be translated.
Related PRs: https://github.com/dof-dss/nidirect-drupal/pull/643, https://github.com/dof-dss/nicsdru_nidirect_theme/pull/258

Translation help block

---

nidirect_landing_pages/nidirect_landing_pages.module

Alter the edit/update forms for blocks in layout builder:
- banners and contact cards don't use the title field - hide it and the display title option
- standard, wide and plain cards must show a title - just hide the display title option
- for other block types (accordions, video and caption, plain card decks, etc) the block title may or may not be displayed
And
- remove container-inline class from the telephone plus fieldsets

Landing page block alterations

---

nidirect_common/inc/preprocess.inc

At present, only certain node types which themselves have a field_banner_image field can show a thin banner from the parent theme (when the node's field_banner_image field is empty).
This small change allows any node to show a thin banner from the parent theme regardless of whether it itself has a field_banner_image field or not.  This allows webforms, publications and other node types to show the thin banner set on the theme for the node.

Enable entities that don't have a field_banner_image to display one.

---

nidirect_landing_pages/nidirect_landing_pages.module

Hide title for video blocks and plain card decks.  
Change field_teaser in blocks to use a textarea rather than single line input.

Landing pages changes

---

nidirect_common/nidirect_common.module

Defensive coding to avoid WSOD on most taxonomy term pages

D8NID-1228

---

nidirect_money_advice_articles/nidirect_money_advice_articles.services.yml
nidirect_money_advice_articles/src/EventSubscriber/PostMigrationSubscriber.php

A bit rough around the edges but it seems to now fix the correct flag value for these so editors can't edit them once imported. Doesn't seem to clash with the general migrate post handler as it checks for the migration id to come from MAS import migration.

D8NID-1253 flagging handler

---

nidirect_money_advice_articles/src/EventSubscriber/PostMigrationSubscriber.php

Now safer by using an inner join on MAS migration map table to ensure only MAS articles locked flag data is purged before re-importing. Means other non-MAS nodes can have locked flags kept without being affected by MAS imports.

Improved flag data deletion

---

nidirect_gp/nidirect_gp.module

Works nicely, once I detected the unadvertised hook in the geocoder module :)
`$this->moduleHandler->alter('geocode_address_string', $address_string);`

Give a regional hint to geocoding if the address string is detected as having a UK postcode present

---

nidirect_related_content/src/RelatedContentManager.php

De-dupe content render array by using the entity id as a key when adding to the collection to be rendered. The ordering isn't an issue as the array is sorted before being handed over to the theme layer.

Remove duplicates from some theme listings

---

nidirect_common/inc/preprocess.inc
nidirect_common/nidirect_common.module
nidirect_dblog/nidirect_dblog.info.yml
nidirect_dblog/nidirect_dblog.module

Create new nidirect_dblog module and move hook_entity_delete processing over from nidirect_common.
Implement nidirect_dblog_cron to override dblog_cron - the new processing is more selective and does not delete certain log entries that we would like to keep (redirect deletion and content updates).
See associated PR https://github.com/dof-dss/nidirect-drupal/pull/780

D8 nid 1363

---

nidirect_webforms/nidirect_webforms.module

The forms only vary by URL, this should cut down on extra cache items for other contexts that aren't expected to give any variance in render ouput.

Set webform node cache context to only vary by URL path

---

nidirect_contacts/src/Plugin/Field/FieldFormatter/GMapsLazyLoadFormatter.php
nidirect_webforms/templates/nidirect-webforms-quiz-answer-feedback.html.twig

Webform quiz feedback twig - remove aria-labels as they replace rather than prefix the content of the element. Use visually hidden spans instead to output text for screen readers.
Google map field formatter - set attributes on map container to help screen readers handle it in an appropriate way.   https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Application_Role.

A11y fixes

---

nidirect_common/nidirect_common.module

dimension1 should be top level parent theme, dimension2 should be all themes minus top level parent - this also helps shorten the char length of dimension2 as there is a 150 byte limit imposed by GA (see https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cd_)

Fix custom dimensions added to GTM dataLayer

---

nidirect_common/src/InvalidateTaxonomyListCacheTags.php
nidirect_landing_pages/nidirect_landing_pages.module

Without this, changing a LP's theme value will leave a dangling redirect which can be pruned away manually easily enough but is causing confusion even for seasoned NIDirect testers, let alone casual editors.
Adding a taxo list to expire too so when the change is made, the taxo list for the theme previously used is also expired as well as a parent term list which landing pages also seem to need.

D8 nid 1388

---

nidirect_landing_pages/nidirect_landing_pages.module

The existing logic for creating theme to landing page redirects was deleting all redirects (then creating a new redirect from the theme) every time the page was updated.  If the page update was creation of a pending draft - all redirects including the theme redirect were deleted.  This fix targets a specific redirect and creates or deletes it only when the page update publishes or unpublishes the page.  If a page is published, an an editor creates a pending draft, the theme redirect remains in place.

D8NID-1447 theme to landing page redirect fix

---

.circleci/config.yml
nidirect_webforms/nidirect_webforms.module

This started out as an accessibility fix for webform "select other" components.  However, it morphed into a PR that fixes the  circleci config.
- Fix for "ERROR: Referenced sniff "SlevomatCodingStandard.ControlStructures.RequireNullCoalesceOperator" does not exist" (see also https://github.com/dof-dss/nidirect-drupal/commit/cf43ffd4006be4b63df001d5e2db5cf2d9312170)
- Fetch the phpcs convenience script from main repo's dev branch instead of the main branch (then we can update it without it being deployed to production)
- Disable deprecated_code checks until extending of @internal class errors are resolved

CircleCI config fixes (plus a11y fix for webform select other components)

---

nidirect_school_closures/nidirect_school_closures.module
nidirect_school_closures/nidirect_school_closures.services.yml
nidirect_school_closures/src/EventSubscriber/HttpHeadersSubscriber.php

But only do this when the school closures render element is detected in the outbound response

School closures feed: set surrogate control max age to match data feed TTL

---

nidirect_breadcrumbs/nidirect_breadcrumbs.module

The mystery of the disappearing breadcrumb trail continues.  Had another incident yesterday where a user reported it was missing.  I tried downloading the db and importing locally - but the trail worked ok. 
Hoping this hook_preprocess_breadcrumb will log an error as soon as breadcrumbs start to disappear on live nodes. I can get logz.io to send an email alert if a log entry about missing breadcrumbs appears ... That's the theory anyway!
Can maybe expand this with additional code to troubleshoot why the breadcrumb is missing?

Log a warning if missing breadcrumb is detected on a node

---

nidirect_common/src/Plugin/Block/TranslationHelpBlock.php

The URI query parameter on the translation help link is not required.  The translation help page JS retrieves the URI to be translated from document.referrer - it does not use the query param.
The presence of the param means the translation help block cannot be cached. It also causes 1000s of unique requests for the translation help page because the page is not being retrieved from Drupal's page cache.

Remove uri query param from translation help link and allow block to be cached

---

nidirect_landing_pages/nidirect_landing_pages.module

This is needed for a new Universal Credit (UC) landing page that acts as the front page of a book. Each page in the book presents a video explaining UC.  Since landing pages have a curated layout, we don't want or need the book nav that Drupal automatically adds.

Hide book nav on landing pages
